[project]
name = "spatial-statistics-final-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bokeh>=3.6.3",
    "folium>=0.19.5",
    "geopandas>=1.0.1",
    "geoviews>=1.14.0",
    "gstools[rust]>=1.6.1",
    "holoviews>=1.20.1",
    "hvplot>=0.11.2",
    "ipywidgets>=8.1.5",
    "jupyterlab>=4.3.5",
    "mapclassify>=2.8.1",
    "matplotlib>=3.10.1",
    "numba>=0.61.0",
    "numpy>=1.26.4",
    "pandas>=2.2.3",
    "polars>=1.24.0",
    "pyarrow>=19.0.1",
    "pydeck>=0.9.1",
    "pykrige>=1.7.2",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "sparse>=0.15.5",
    "xarray>=2025.1.2",
]

[project.optional-dependencies]
cuda12 = ["cupy-cuda12x>=13.4.0", "cupy-xarray>=0.1.4", "cuvs-cu12>=25.2.1"]

[tool.uv.sources]
cupy-xarray = { git = "https://github.com/xarray-contrib/cupy-xarray.git" }
cuvs-cu12 = { index = "nvidia" }

[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com"
explicit = true
